'' Normal and Calibration Cassette Properties
#define NUM_ROWS 8
#define NUM_COLUMNS 12

#define CASSETTE_ROW_HEIGHT -15

'' Distance from cassette surface to sample surface if pin deep in cassette
#define SAMPLE_DIST_PIN_DEEP_IN_CAS 3.2
'' Distance error tolerance when pin is not sitting deep in cassette port
#define TOLERANCE_FROM_PIN_DEEP_IN_CAS 1.0
'' PROBE_DISTANCE_FOR_CAS_PORT = PIN_DEEP_IN_CAS_DISTANCE + TOLERANCE_FROM_PIN_DEEP_IN_CAS
#define PROBE_DISTANCE_FOR_CAS_PORT 4.2

