
'' Go speed settings for Probing Recheck
#define SUPERSLOW_GO_ACCEL 5
#define SUPERSLOW_GO_DEACCEL 5
#define SUPERSLOW_GO_SPEED 1
'' Move speed settings for Probing Recheck
#define SUPERSLOW_MOVE_ACCEL 5
#define SUPERSLOW_MOVE_DEACCEL 5
#define SUPERSLOW_MOVE_SPEED 1

'' Go speed settings for Probing (Same as very slow speed)
#define PROBE_GO_ACCEL 24
#define PROBE_GO_DEACCEL 24
#define PROBE_GO_SPEED 36
'' Move speed settings for Probing (Same as very slow speed)
#define PROBE_MOVE_ACCEL 51
#define PROBE_MOVE_DEACCEL 51
#define PROBE_MOVE_SPEED 72

'' Go speed settings for INSIDE_LN2
#define INSIDE_LN2_GO_ACCEL 30
#define INSIDE_LN2_GO_DEACCEL 30
#define INSIDE_LN2_GO_SPEED 90
'' Move speed settings for INSIDE_LN2
#define INSIDE_LN2_MOVE_ACCEL 150
#define INSIDE_LN2_MOVE_DEACCEL 150
#define INSIDE_LN2_MOVE_SPEED 200

'' Go speed settings for OUTSIDE_LN2
#define OUTSIDE_LN2_GO_ACCEL 40
#define OUTSIDE_LN2_GO_DEACCEL 40
#define OUTSIDE_LN2_GO_SPEED 100
'' Move speed settings for OUTSIDE_LN2
#define OUTSIDE_LN2_MOVE_ACCEL 4000
#define OUTSIDE_LN2_MOVE_DEACCEL 4000
#define OUTSIDE_LN2_MOVE_SPEED 1000

